### ISSUE TITLE
Remove the use of Proxy

### ISSUE THREAD

**Issue by thaume** [RobinQu/koa-oauth2orize#3]
Hey there !

I was wondering if you could be interested in removing the use of Proxy in this module ? This would be interesting to be able to run it with iojs without the need to add a feature flag :)

Example here: https://github.com/rkusa/koa-passport/commit/69c75191c15fba42da6d7088e59733e719874c77#diff-c185b99ab8033f79ffee98e22fde6d32L144

**Comment by ButuzGOL** [comment]
+1

**Comment by RobinQu** [comment]
Too busy at work. PR is always welcome.
Or I will manage to review this issue at weekend.

**Comment by thaume** [comment]
Alright cool, I'll get start a PR. The module is working great btw, just want to remove the '--harmony_proxies' from my io.js app in production :)

**Comment by aguegu** [comment]
run into this Proxy issue too with iojs.

**Comment by DaAwesomeP** [comment]
`Proxy is not defined` in iojs.

**Comment by DaAwesomeP** [comment]
Does anyone else have a problem when tying in Nginx? If I restart the server, then it fails with `EADDRINUSE` when Nginx is expecting something for its reverse proxy at that address and port.

**Comment by thaume** [comment]
Proxy in js is just a way to access an object's properties. Your problem
shouldn't be linked to that. Make sure you don't start nginx or node while
there's already an instance running.

**Comment by DaAwesomeP** [comment]
My bad. I told `app.listen()` to use `127.0.0.1:3000` and it took it as if it were a path (for a UNIX socket) instead of _host:port_. That file would persist sometimes, so the socket was technically in use. Nginx and the Proxy thing had nothing to do with it.

@thaume any way to avoid the flag yet? I've only just started using this library and I am definitely annoyed a tad by it.

**Comment by thaume** [comment]
"Can I use" is always great for getting support information across platforms : http://kangax.github.io/compat-table/es6/#Proxy

You'll see that Proxies are not even supported in Chrome 46 (which is canary right now). So for now you'll have to keep the flag on :) Node.js 4.0.0 will bring a lot of really cool features, but no Proxy yet.

**Comment by DaAwesomeP** [comment]
@thaume I'm not sure that I'm following you completely. Are you saying that if the `Proxy` isn't executed on the server side that it will need to be done on the client side?

**Comment by thaume** [comment]
Im just saying that the Proxy feature of es6 is not available in chrome for
now (and not for quite some time). Node is based on V8 (the js engine of
Chrome), so it gets es6 features once v8 implements them.

Now, the Proxy I refer to in this issue has nothing to do with a
load-balancer/reverse proxy like Nginx or HAproxy. A proxy in Node/js is
just a way to access an object's properties. You can learn more about hem
here : http://www.2ality.com/2014/12/es6-proxies.html?m=1

**Comment by RobinQu** [comment]
Any better solution?
I don't maintain a list of property descriptor to do that.

**Comment by RobinQu** [comment]
Proxy in iojs needs some shim to work.

https://github.com/nodejs/node/issues/761

Will try https://github.com/tvcutsem/harmony-reflect

**Comment by thaume** [comment]
Hey @RobinQu actually no I don't :) and I agree with you, Proxy is the right tool for the job here. harmony-reflect seems fine ! Need help to setup the PR ?

**Comment by RobinQu** [comment]
@thaume  PR is always welcomed!
